export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_CART_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_PRODUCT';
export const DELETE_CART_PRODUCT = 'DELETE_PRODUCT';
