export const FETCH_USER_START = 'FETCH_USER_START';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';

export const TOGGLE_CART_DROPDOWN = 'TOGGLE_CART_DROPDOWN';
export const ADD_CART_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_CART_PRODUCT = 'REMOVE_PRODUCT';
export const DELETE_CART_PRODUCT = 'DELETE_PRODUCT';
