export const actionType = {
  GET_ALL_PRODUCTS: 'GET_ALL_PRODUCTS',
  GET_NEWEST_PRODUCTS: 'GET_NEWEST_PRODUCTS',
  GET_BESTSELLING_PRODUCTS: 'GET_BESTSELLING_PRODUCTS',
  GET_PRODUCT: 'GET_PRODUCT',
  GET_SIMILAR_PRODUCTS: 'GET_SIMILAR_PRODUCTS',
  CREATE_PRODUCT: 'CREATE_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  SET_SEARCH_FILTERS: 'SET_SEARCH_FILTERS',
};
