export const actionType = {
  API_CALL_START: 'API_CALL_START',
  API_CALL_SUCCESS: 'API_CALL_SUCCESS',
  API_CALL_FAIL: 'API_CALL_FAIL',
  API_CALL_RESET: 'API_CALL_RESET',
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  UPDATE_USER: 'UPDATE_USER',
  GET_ALL_ROOMS: 'GET_ALL_ROOMS',
};
